In [5]:
import numpy as np
#lista multiples tipos de datos
#Array elementos homogenios de un mismo tipo de dato
#python 
#listas no pueden manejar operacioes aritmeticas directamente
lista=[1,3,5] #coleccion de datos
print(lista)
lista.append(7)#funciona 
#numpy
#arrays puede manejar directamnte operaciones aritmeticas
matriz = np.array([2,4,6]) #cada uno de los elementos en una matriz es independiente
#matriz.append(8)#no funciona 
matriz = matriz + np.array([8])#cada uno de los elementos son ubicados en un espacio de memoria
print (matriz)


[1, 3, 5]
[10 12 14]


In [6]:
a=[1,2,3]
b=[4,5,6]
print(a+b)
#une las listas pporque no se pueden realizar operacion de manera directa

[1, 2, 3, 4, 5, 6]


In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print (a * b)
print (a + b)

[ 4 10 18]
[5 7 9]
