In [5]:
import numpy as np
#crear matriz 2d y 3d
matriz2d = np.array([[1,2,3],[4,5,6]])
print(matriz2d)

[[1 2 3]
 [4 5 6]]


In [9]:
#extraer informacion de listas a matrices
lista = [[1,2,3,4,5],[6,7,8,9,0]]
matriz = np.array(lista)
print(matriz)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [12]:
#crear matris de manera rapida
#arange genera un rango depositas un valor (15) la cantidad de elementos que va a haber reshape("filas","columnas")
m = np.arange(15).reshape(5,3)
print(m)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
