In [3]:
import numpy as np
m = np.arange(20).reshape(4,5)
print(m.shape)#cuantas filas y columnas hay en la matriz
print(m.ndim)#cuantas dimenciones tiene la matriz
print(m.size)#cuantos elementos tiene esta matriz
print(m)

(4, 5)
2
20
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
#matriz llena de seros
m = np.zeros((3,4))
print(m)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#("desde","hasta","cuantos")
m= np.linspace(99,88,25)
print(m)

[99.         98.54166667 98.08333333 97.625      97.16666667 96.70833333
 96.25       95.79166667 95.33333333 94.875      94.41666667 93.95833333
 93.5        93.04166667 92.58333333 92.125      91.66666667 91.20833333
 90.75       90.29166667 89.83333333 89.375      88.91666667 88.45833333
 88.        ]


In [10]:
#("lados","filas","columnas")
m = np.arange(24).reshape(3,4,2)
print(m)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
