In [1]:
import numpy as np
m= np.arange(24).reshape(4,6)
print(m[3,4])
print(m)

22
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [3]:
#ordenar elementos
m1 = np.array([90,7,9,3,2,1])
print(np.sort(m1))

[ 1  2  3  7  9 90]


In [4]:
#elevar elementos a n potencia
m1=np.array([2,3])
print(np.power(m1,3))

[ 8 27]


In [6]:
#con condiciones
m1=np.array([2,3,4,5,6,7])
print(np.array(m1>=4))

[False False  True  True  True  True]


In [7]:
#encontrar el valor maximo y minimo que se encuentra en la mtriz
m1= np.array([2,3,4,5,6,7])
print(np.max(m1))
print(np.min(m1))

7
2


In [8]:
#combinar 2 matrices
m1= np.array([1,2,3,4,5])
m2= np.array([11,22,33,44,55])
print(np.concatenate((m1,m2)))

[ 1  2  3  4  5 11 22 33 44 55]


In [13]:
m1= np.array([[1,2],[3,4]])
m2= np.array([[5,6],[7,8]])
print(m1+m2)#suma resta multiplicacion division
print(m1.dot(m2))#multiplica de forma horizontal la otra matriz de forma vertical
print(m1+2)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[3 4]
 [5 6]]
