In [10]:
import numpy as np
m=np.random.rand(2,2)
print(m)
#numeros enteros aleatorios en una matriz
m=np.random.randint(10,size=(2,2,2))
print(m)

[[0.69401018 0.41408055]
 [0.05430427 0.40517332]]
[[[8 1]
  [7 4]]

 [[5 6]
  [1 3]]]


In [16]:
#escoje aleatorimente cualquier de los elementos que esta ahi
m=np.random.choice([3,5,9,5,1],size=(2,3))
print(m)

[[9 1 3]
 [9 9 5]]


In [21]:
m=np.random.choice([4,2,8,10],p=[0.25,0.25,0.25,0.25],size=(5,10))
print(m)

[[ 8 10  8  8 10  2 10 10  8  4]
 [10  2 10 10 10  4  4  2 10  4]
 [10  4 10  2  8  8  4 10 10  4]
 [ 8  4 10 10 10  8  4  4 10  4]
 [ 4  4  8  2  8  4  8  4  4 10]]
