In [5]:
#axis 1 columna axis 0 filas
import numpy as np
m= np.array([[0,1,2],[4,2,3]])
print(m)
print("")
print(np.sum(m, axis=0))#Suma filas
print(np.sum(m, axis=1))#Suma columnas

[[0 1 2]
 [4 2 3]]

[4 3 5]
[3 9]


In [11]:
import numpy as np
m1=np.array([[1,1],[1,1]])
m2=np.array([[8,8],[8,8]])
print(m1,m2)
print (np.concatenate([m1,m2], axis=0))#concatena como filas
print (np.concatenate([m1,m2], axis=1))#concatena como columnas

[[1 1]
 [1 1]] [[8 8]
 [8 8]]
[[1 1]
 [1 1]
 [8 8]
 [8 8]]
[[1 1 8 8]
 [1 1 8 8]]
