In [8]:
import numpy as np
#axis 1 filas axis 0 columnass
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print("")
#valor minimo
print(np.amin(m))
#valor maximo
print(np.amax(m))
#valor minimo o maximo de filas
print(np.amax(m,1))#valor maximo de columnas
print(np.amax(m,0))#valor maximo de filas
print(np.amin(m,1))#valor minimo de columnas
print(np.amin(m,0))#valor minimo de filas
#encontrar rango elemento maximo menos minomo
print(np.ptp(m,axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
9
[3 6 9]
[7 8 9]
[1 4 7]
[1 2 3]
[2 2 2]
